### PR TITLE
Removed Mitsoko from include paths

### PR DESCRIPTION
**Pull request by DonaldTrump88**
Please, approve the changes. So once root folder is set as include path. Then Mitsoko is unneccessary.

### CODE REVIEW

**Comment by fnc12** [comment]
Why? `Mitsoko` exists in include path cause all `Core` is set in user header include paths.

**Comment by ElephantInTheRoomFirst** [comment]
It is not standard practice for library with header and source. I can be complied separately also. 
I saw includes in Android.mk LOCAL_C_INCLUDES := $(LOCAL_PATH)/../../../../../Core/ \
					$(LOCAL_PATH)/../../../../../Core/libs/ 
It includes everything(kind of catch all) in the path. The application should include Mitsoko using LOCAL_C_INCLUDES := $(LOCAL_PATH)/../../../../../Core/Mitsoko \. 
Like in case of standard library, include path is path to library e.g. 
This is paths of string.h

what do you think? 
```
/usr/include/string.h
/usr/include/bits/string.h
/usr/include/c++/4.8.2/bits/basic_string.h
/usr/include/c++/4.8.2/ext/vstring.h
/usr/include/linux/string.h
/usr/include/linux/netfilter/xt_string.h
/usr/include/qt5/QtCore/qstring.h
```

2. If I want to include  qstring.h, then I add QtCore in package first and use #include "QString".

**Comment by fnc12** [comment]
No, Mitsoko just a part of a core. Core also can include libs, DataModel, Services and any other user code. Any core code can be accessed easily by `#include "DataModel/MyClass.hpp"`, `#include "Services/MyStorage.hpp", etc. Check the template project https://github.com/fnc12/mitsoko-template

**Comment by ElephantInTheRoomFirst** [comment]
ok

**Pull request closed without merging**
